server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.103:8848 #配置Nacos地址
    # 路由配置
    gateway:
      routes:
        - id: cloud-nacos-user # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8006          #匹配后提供服务的路由地址
          uri: lb://cloud-nacos-user #匹配后使用负载均衡提供服务的路由地址
          predicates:
            - Path=/nacos/user/discovery/**         # 断言，路径相匹配的进行路由

        - id: cloud-nacos-user2 # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8006          #匹配后提供服务的路由地址
          uri: lb://cloud-nacos-user #匹配后使用负载均衡提供服务的路由地址
          predicates:
            - Path=/nacos/user/gateway/**         # 断言，路径相匹配的进行路由
            # - After=2022-04-16T17:07:52.284+08:00[Asia/Shanghai] # 在指定时间之后可以访问
            # - Before=2022-04-16T17:07:52.284+08:00[Asia/Shanghai] # 在指定时间之前可以访问
            # - Between=2022-04-16T17:07:52.284+08:00[Asia/Shanghai], 2022-04-16T17:09:58.441+08:00[Asia/Shanghai] # 在指定时间之间可以访问
            # - Cookie=chocolate, ch.p # Cookie中有一个chocolate的属性且值能够与ch.p进行正则匹配
            # - Header=X-Request-Id, \d+ #  Header中有一个X-Request-Id的属性且值能够与\d+进行正则匹配
            # - Method=GET,POST # 规定请求的方法必须为GET和POST
            # 一共有11中匹配检验规定

# spring-boot-starter-actuator配置
management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露