server:
  port: 7073
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.103:8848 #配置Nacos地址
    stream:
      kafka:
        binder:
          brokers: 192.168.0.103:9092,192.168.0.103:9093,192.168.0.103:9094
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyTopic # 表示要使用的Topic名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          group: consumer-group-a
# spring-boot-starter-actuator配置
management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露