server:
  port: 7071
spring:
  application:
    name: cloud-sentinel-producer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.103 #配置Nacos地址
    sentinel:
      eager: true # 取消Sentinel控制台懒加载(默认false)
      transport:
        dashboard: 192.168.0.103:8080 # Sentinel 控制台地址
        port: 8719 #应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
        client-ip: 192.168.0.101
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.0.103 # 配置Nacos地址
            dataId: sentinel-service-persistence # 配置文件的Data Id
            groupId: DEFAULT_GROUP # 配置文件的组别
            namespace: 628daf06-c468-4f32-a825-582390a85b53 # 配置文件的命名空间
            data-type: json # 配置文件的类型
            rule-type: flow
  zipkin:
    base-url: http://192.168.0.103:9411
  sleuth:
    sampler:
      probability: 1
feign:
  sentinel:
    enabled: true