server:
  port: 8005
spring:
  application:
    name: cloud-hystrix-user
# 日志文件配置
logging:
  file:
    name: log/cloud-hystrix-user.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} : [%thread] : %-5level : %logger{50} : %msg%n'

eureka:
  client:
    #表示是否将自己注册进Eureka server默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: cloud-hystrix-user
    #访问路径可以显示IP地址
    prefer-ip-address: false
# spring-boot-starter-actuator配置
management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露