server:
  port: 8201
spring:
  application:
    name: cloud-sentinel-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.103 #配置Nacos集群地址
    sentinel:
      eager: false # 取消Sentinel控制台懒加载(默认false)
      transport:
        dashboard: 192.168.0.103:8080 # Sentinel 控制台地址
        port: 8719 #应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
        client-ip: 192.168.0.101
  zipkin:
    base-url: http://192.168.0.103:9411
  sleuth:
    sampler:
      probability: 1

# spring-boot-starter-actuator配置
management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露
feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持